#!/data/data/com.termux/files/usr/bin/bash
echo "TERMUX YT MP4 DOWNLOADER - by @LaelsonCG"
echo "Iniciando instalação..."

# Atualiza os repositórios
pkg update -y

# Instala o Python e o pip
pkg install python3 -y

# Instala o yt-dlp
pip3 install yt-dlp

# Baixa script de download
wget https://raw.githubusercontent.com/LaelsonCG/termux-youtube-downloader/main/yt-mp4.py

# Adiciona permissões de execução
chmod +x yt-mp4.py
cp yt-mp4.py /data/data/com.termux/files/usr/bin/yt

echo "Instalação concluída com sucesso!"
echo "Agora você pode baixar vídeos com: ./yt-mp4.py URL_do_vídeo"
echo "Ou apenas assim: yt URL_DO_VIDEO"
